// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMJ0FgblUXSvj76Vk_q6hPZXtO8Wl0Et8',
    appId: '1:1001687924361:web:63078f3193350330fed058',
    messagingSenderId: '1001687924361',
    projectId: 'touristpro-325d6',
    authDomain: 'touristpro-325d6.firebaseapp.com',
    storageBucket: 'touristpro-325d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEhRUTbb5Gwht4xyKqxbCAl9b0JXx72h4',
    appId: '1:1001687924361:android:2e4f1749918bc618fed058',
    messagingSenderId: '1001687924361',
    projectId: 'touristpro-325d6',
    storageBucket: 'touristpro-325d6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMJ0FgblUXSvj76Vk_q6hPZXtO8Wl0Et8',
    appId: '1:1001687924361:web:22431d8c135873e2fed058',
    messagingSenderId: '1001687924361',
    projectId: 'touristpro-325d6',
    authDomain: 'touristpro-325d6.firebaseapp.com',
    storageBucket: 'touristpro-325d6.firebasestorage.app',
  );
}
